let revenueCatAPIKey = "appl_rWnaflTkNLwwDOUgxvIaEnnOYzu"
let revenueCatMonthlyProductID = "toptracks_099_1month"
let revenueCatYearlyProductID = "toptracks_999_1year"
let revenueCatMonthlyPackageID = "Monthly"
let revenueCatYearlyPackageID = "Yearly"
